version: "3"

services:
  # here a lot of other stuff
  integration_tests:
    build:
      context: .
    depends_on:
      - billing
      - rabbitmq

  billing:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: wallet
    expose:
      - 5432

    #DEBUG_MODE: ports:
    #DEBUG_MODE:   - 8132:5432

  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - 5672

    #DEBUG_MODE: ports:
    #DEBUG_MODE:   - 8172:5672
